[package]
name = "rust_rocksdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bincode = "2.0.0-rc.3"
bytes = { version = "1.4.0", features = ["serde"] }
